export const FORM_PROJECT = 'FORM_PROJECT';
export const GET_PROJECTS = 'GET_PROJECTS';
export const ADD_PROJECT = 'ADD_PROJECT';
export const VALIDATE_FORM = 'VALIDATE_FORM';
export const REMOVE_ERROR = 'REMOVE_ERROR';
export const ACTUAL_PROJECT = 'ACTUAL_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const PROJECT_ERROR = 'PROJECT_ERROR';


export const TASK_PROJECT = 'TASK_PROJECT';
export const ADD_TASK_PROJECT = 'ADD_TASK_PROJECT';
export const VALIDATE_TASK_PROJECT = 'VALIDATE_TASK_PROJECT';
export const REMOVE_ERROR_TASK = 'REMOVE_ERROR_TASK';
export const DELETE_TASK = 'DELETE_TASK';
export const UPDATE_STATE_TASK = 'UPDATE_STATE_TASK';
export const ACTUA_TASK = 'ACTUA_TASK';
export const UPDATE_TASK = 'UPDATE_TASK';
export const CLEAN_TASK = 'CLEAN_TASK';

export const VIEW_ALERT = 'VIEW_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';
export const GET_USER = 'GET_USER';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOG_OUT = 'LOG_OUT';

    
